<?php

require ("admin_load.php");
	
	$mconfig = new MagratheaConfig();
	$mconfig->setPath(__DIR__);
	$mconfig->setFile("/../configs/magrathea_objects.conf");
	$objdata = $mconfig->getConfig();

	$env = MagratheaConfigStatic::GetConfig("general/use_environment");
	$site_path = MagratheaConfigStatic::GetConfig($env."/site_path");
	$models_dir = $site_path."Models";
	$base_dir = $models_dir."/Base";

	echo "<br/><pre>";
	if( !is_dir($base_dir) ){
		mkdir($base_dir);
	}
	foreach( $objdata as $object => $data ){
		if( $object == "relations" ) continue;
		echo "- Object: ".$object."\n\t";
		$obj_fields = array();
		foreach($data as $key => $item){
			if( substr($key, -6) == "_alias" ){
				$field_name = substr($key, 0, -6);
				if( $field_name == "created_at" || $field_name == "updated_at" ) continue;
				array_push($obj_fields, $field_name);
			}
		}

		$relations = array();
		$relations = GetRelationsByObject($object);
		$relations_properties = "";
		$relations_functions = "";
		foreach($relations as $rel){
			$relations_properties .= "\t\t\$this->relations[\"properties\"][\"".$rel["rel_property"]."\"] = null;\n";
			$relations_properties .= "\t\t\$this->relations[\"methods\"][\"".$rel["rel_property"]."\"] = \"".$rel["rel_method"]."\";\n";
			if( $rel["rel_type"] == "belongs_to" ) {
				$relations_properties .= "\t\t\$this->relations[\"methods_set\"][\"".$rel["rel_property"]."\"] = \"Set".$rel["rel_object"]."\";\n";
			}

			if( $rel["rel_type"] == "has_and_belongs_to_many" ){
				$field = $rel["rel_field"];
				$splitField = explode('#', $field);
				$rel_table = $splitField[0];
				$obj1 = explode(":", $splitField[1]);
				$obj2 = explode(":", $splitField[2]);
				if( $obj1[0] == $object ){
					$rel_obj_this = $obj1;
					$rel_obj_other = $obj2;
				} else {
					$rel_obj_this = $obj2;
					$rel_obj_other = $obj1;
				}
				$relations_properties .= "\t\t\$this->relations[\"relational_table\"][\"".$rel["rel_property"]."\"] = \"".$rel_table."\";\n";
			}

			
			// getter:
			$relations_functions .= "\tpublic function ".$rel["rel_method"]."(){\n";
			if( $rel["rel_type"] == "belongs_to" ) {
				$relations_functions .= "\t\t\$this->relations[\"properties\"][\"".$rel["rel_property"]."\"] = new ".$rel["rel_object"]."(\$this->".$rel["rel_field"].");\n";
			} else if ( $rel["rel_type"] == "has_many" ) {
				$relations_functions .= "\t\t\$pk = \$this->dbPk;\n";
				$relations_functions .= "\t\t\$this->relations[\"properties\"][\"".$rel["rel_property"]."\"] = ".$rel["rel_object"]."ControlBase::GetWhere(array(\"".$rel["rel_field"]."\" => \$this->\$pk));\n";
			} else if( $rel["rel_type"] == "has_and_belongs_to_many" ){
				$relations_functions .= "\t\t\$relational_object = new ".$rel["rel_object"]."();\n";
				$relations_functions .= "\t\t\$query = MagratheaQuery::Create()->Obj(\$relational_object)->Join(\" INNER JOIN \".\$this->relations[\"relational_table\"][\"".$rel["rel_property"]."\"].\" ON \".\$this->relations[\"relational_table\"][\"".$rel["rel_property"]."\"].\".".$rel_obj_other[1]." = \".\$relational_object->dbTable.\".\".\$relational_object->GetPkName().\" \")->Where(array(\$this->relations[\"relational_table\"][\"".$rel["rel_property"]."\"].\".".$rel_obj_this[1]."\" => \$this->GetID()));\n";
				$relations_functions .= "\t\t\$this->relations[\"properties\"][\"".$rel["rel_property"]."\"] = ".$rel["rel_object"]."ControlBase::Run(\$query);\n";
			}
			$relations_functions .= "\t\treturn \$this->relations[\"properties\"][\"".$rel["rel_property"]."\"];\n";
			$relations_functions .= "\t}\n";

			// setter:
			if( $rel["rel_type"] == "belongs_to" ) {
				$relations_functions .= "\tpublic function Set".$rel["rel_object"]."(\$value){\n";
					$relations_functions .= "\t\t\$this->relations[\"properties\"][\"".$rel["rel_object"]."\"] = \$value;\n";
					$relations_functions .= "\t\tif(is_a(\$value, \"MagratheaModel\")){\n";
						$relations_functions .= "\t\t\t\$this->".$rel["rel_field"]." = \$value->GetID();\n";
					$relations_functions .= "\t\t}\n";
				$relations_functions .= "\t}\n";
			}
			if( $rel["rel_type"] == "has_and_belongs_to_many" ){
				$relations_functions .= "\tpublic function Add".$rel["rel_object"]."(\$value){\n";
					$relations_functions .= "\t\t\$id".$rel["rel_object"]." = \$value->GetID();\n";
					$relations_functions .= "\t\t\$id".$object." = \$this->GetID();\n";
					$relations_functions .= "\t\t\$mquery = MagratheaQuery::Insert()->Table(\$this->relations[\"relational_table\"][\"".$rel["rel_property"]."\"])->Values(array(\"".$rel_obj_other[1]."\" => \$id".$rel["rel_object"].", \"".$rel_obj_this[1]."\" => \$id".$object."));\n";
					$relations_functions .= "\t\treturn ActorControl::Run(\$mquery);\n";
				$relations_functions .= "\t}\n\n";
			}


		} // close foreach relations
	
		$code = "<?php\n\n";
		$code .= "## FILE GENERATED BY MAGRATHEA.\n## SHOULD NOT BE CHANGED MANUALLY\n\n";

		$code .= "class ".$object."Base extends MagratheaModel implements iMagratheaModel {\n\n";
		
		$code .= "\tpublic \$".implode(", $", $obj_fields).";\n";
		$code .= "\tprotected \$lazyLoad = ".$data["lazy_load"].";\n\n";
		
		$code .= "\tpublic function __construct( \$id=0 ){ \n";
			$code .= "\t\t\$this->Start();\n";
			$code .= "\t\tif( !empty(\$".$data["db_pk"].") ){\n";
				$code .= "\t\t\t\$pk = \$this->dbPk;\n";
				$code .= "\t\t\t\$this->\$pk = \$".$data["db_pk"].";\n";
				$code .= "\t\t\t\$this->GetById(\$".$data["db_pk"].");\n";
			$code .= "\t\t}\n";
		$code .= "\t}\n";
		$code .= "\tpublic function Start(){\n";
			$code .= "\t\t\$this->dbTable = \"".$data["table_name"]."\";\n";
			$code .= "\t\t\$this->dbPk = \"".$data["db_pk"]."\";\n";
			foreach($obj_fields as $f){
				$code .= "\t\t\$this->dbValues[\"".$f."\"] = \"".$data[$f."_type"]."\";\n";
				if( !empty($data[$f."_alias"]) )
					$code .= "\t\t\$this->dbAlias[\"".$data[$f."_alias"]."\"] = \"".$f."\";\n";
			}
			
			$code .= "\n".$relations_properties;
		$code .= "\t}\n\n";

		$code .= "\t// >>> relations:\n".$relations_functions."\n";

		$code .= "}\n\n";
		
		$code .= "class ".$object."ControlBase extends MagratheaModelControl {\n";
			$code .= "\tprotected static \$modelName = \"".$object."\";\n";
			$code .= "\tprotected static \$dbTable = \"".$data["table_name"]."\";\n";
		$code .= "}\n";		

		$code .= "?>";

		$base_filename = $object."Base.php";
		if( writeFile($base_dir, $base_filename, $code) ){
			echo "\t".$base_filename." was successfully created! =)\n\n";
		} else {
			echo "\tOh, boy... there was an error trying to write ".$base_filename."... =(\n\t";
			echo "\tPlease, assure that ".$base_dir." is writable by PHP!\n\n";
		}
		
		$filename = $object.".php";
		if( !file_exists($models_dir."/".$filename) ){
			$code2 = "<?php\n\n";
			$code2 .= "include(__DIR__.\"/Base/".$base_filename."\");\n\n";

			$code2 .= "class ".$object." extends ".$object."Base {\n";
			$code2 .= "\t// your code goes here!\n";
			$code2 .= "}\n\n";
			
			$code2 .= "class ".$object."Control extends ".$object."ControlBase {\n";
			$code2 .= "\t// and here!\n";
			$code2 .= "}\n\n";
			
			$code2 .= "?>";
			if( writeFile($models_dir, $filename, $code2) ){
				chmod($models_dir."/".$filename, 0777);
				echo "\t".$filename." was created as well. This way, things gets much easier for you! =)\n\n";
			}
		}

	} // close for each Object
	echo "</pre>";

function writeFile($filepath, $filename, $content){
	if(file_exists($filepath."/".$filename)){
		unlink($filepath."/".$filename);
	}
	if (!$handle = @fopen($filepath."/".$filename, 'w')) { 
		return false; 
	} 
	if (!fwrite($handle, $content)) { 
		return false; 
	} 
	fclose($handle); 
	return true; 
}

?>


<?php
/*

<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class PizzariaBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $subtitle, $logo;
	protected $lazyLoad = true;

	public function __construct( $id=0 ){ 
		$this->Start();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function Start(){
		$this->dbTable = "pizzaria";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["subtitle"] = "text";
		$this->dbAlias["slogan"] = "subtitle";
		$this->dbValues["logo"] = "string";
		$this->relations["properties"]["PizzariaLocations"] = null;
		$this->relations["methods"]["PizzariaLocations"] = "GetPizzariaLocations";
	}

	public function GetPizzariaLocations(){
		$pk = $this->dbPk;
		$this->relations["properties"]["PizzariaLocations"] = PizzariaLocationControlBase::GetWhere(array("pizzaria_id" => $this->$pk));
		return $this->relations["properties"]["PizzariaLocations"];
	}

}

class PizzariaControlBase extends MagratheaModelControl {
	protected static $modelName = "Pizzaria";
	protected static $dbTable = "pizzaria";
}

?>
*/

?>



