<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class ActorBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $foto_id;
	protected $lazyLoad = true;

	public function __construct( $id=0 ){ 
		$this->Start();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function Start(){
		$this->dbTable = "tab_actors";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["foto_id"] = "int";
		$this->dbAlias["foto"] = "foto_id";

		$this->relations["properties"]["Movies"] = null;
		$this->relations["methods"]["Movies"] = "GetMovies";
		$this->relations["relational_table"]["Movies"] = "rel_movies_actors";
	}

	// >>> relations:
	public function GetMovies(){
		$relational_object = new Movie();
		$query = MagratheaQuery::Create()->Obj($relational_object)->Join(" INNER JOIN ".$this->relations["relational_table"]["Movies"]." ON ".$this->relations["relational_table"]["Movies"].".movie_id = ".$relational_object->dbTable.".".$relational_object->GetPkName()." ")->Where(array($this->relations["relational_table"]["Movies"].".actor_id" => $this->GetID()));
		$this->relations["properties"]["Movies"] = MovieControlBase::Run($query);
		return $this->relations["properties"]["Movies"];
	}
	public function AddMovie($value){
		$idMovie = $value->GetID();
		$idActor = $this->GetID();
		$mquery = MagratheaQuery::Insert()->Table($this->relations["relational_table"]["Movies"])->Values(array("movie_id" => $idMovie, "actor_id" => $idActor));
		return ActorControl::Run($mquery);
	}


}

class ActorControlBase extends MagratheaModelControl {
	protected static $modelName = "Actor";
	protected static $dbTable = "tab_actors";
}
?>