<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class DirectorBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name;
	protected $lazyLoad = true;

	public function __construct( $id=0 ){ 
		$this->Start();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function Start(){
		$this->dbTable = "tab_directors";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";

		$this->relations["properties"]["Movies"] = null;
		$this->relations["methods"]["Movies"] = "GetMovies";
	}

	// >>> relations:
	public function GetMovies(){
		$pk = $this->dbPk;
		$this->relations["properties"]["Movies"] = MovieControlBase::GetWhere(array("director_id" => $this->$pk));
		return $this->relations["properties"]["Movies"];
	}

}

class DirectorControlBase extends MagratheaModelControl {
	protected static $modelName = "Director";
	protected static $dbTable = "tab_directors";
}
?>