<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class MovieBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $year, $director_id;
	protected $lazyLoad = true;

	public function __construct( $id=0 ){ 
		$this->Start();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function Start(){
		$this->dbTable = "tab_movies";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbAlias["title"] = "name";
		$this->dbValues["year"] = "int";
		$this->dbValues["director_id"] = "int";

		$this->relations["properties"]["Actors"] = null;
		$this->relations["methods"]["Actors"] = "GetActors";
		$this->relations["relational_table"]["Actors"] = "rel_movies_actors";
		$this->relations["properties"]["Director"] = null;
		$this->relations["methods"]["Director"] = "GetDirector";
		$this->relations["methods_set"]["Director"] = "SetDirector";
	}

	// >>> relations:
	public function GetActors(){
		$relational_object = new Actor();
		$query = MagratheaQuery::Create()->Obj($relational_object)->Join(" INNER JOIN ".$this->relations["relational_table"]["Actors"]." ON ".$this->relations["relational_table"]["Actors"].".actor_id = ".$relational_object->dbTable.".".$relational_object->GetPkName()." ")->Where(array($this->relations["relational_table"]["Actors"].".movie_id" => $this->GetID()));
		$this->relations["properties"]["Actors"] = ActorControlBase::Run($query);
		return $this->relations["properties"]["Actors"];
	}
	public function AddActor($value){
		$idActor = $value->GetID();
		$idMovie = $this->GetID();
		$mquery = MagratheaQuery::Insert()->Table($this->relations["relational_table"]["Actors"])->Values(array("actor_id" => $idActor, "movie_id" => $idMovie));
		return ActorControl::Run($mquery);
	}

	public function GetDirector(){
		$this->relations["properties"]["Director"] = new Director($this->director_id);
		return $this->relations["properties"]["Director"];
	}
	public function SetDirector($value){
		$this->relations["properties"]["Director"] = $value;
		if(is_a($value, "MagratheaModel")){
			$this->director_id = $value->GetID();
		}
	}

}

class MovieControlBase extends MagratheaModelControl {
	protected static $modelName = "Movie";
	protected static $dbTable = "tab_movies";
}
?>