<?php

#######################################################################################
####
####	MAGRATHEA PHP
####	v. 1.0
####
####	Magrathea by Paulo Henrique Martins
####	Platypus technology
####
#######################################################################################
####
####	Database Class
####	Database connection class
####	
####	created: 2012-12 by Paulo Martins
####
#######################################################################################


class MagratheaConfigStatic {
	private static $path = __DIR__;
	private static $config_file_name = "configs/magrathea.conf";
	private static $configs = null;
	private function loadFile(){
		if(!file_exists(self::$path."/../".self::$config_file_name)){
			throw new MagratheaException("Config file could not be found - ".self::$path."/../".self::$config_file_name);
		}
	}
	
	public static function getConfig($config_name=""){
		if( self::$configs == null ){
			self::loadFile();
			self::$configs = parse_ini_file(self::$path."/../".self::$config_file_name, true);
			if( !self::$configs ){
				throw new MagratheaException("There was an error trying to load the config file.<br/>");
			}
		}
		if( empty($config_name) ){
			return self::$configs;
		} else {
			$c_split = explode("/", $config_name);
			return ( count($c_split) == 1 ? self::$configs[$config_name] : self::$configs[$c_split[0]][$c_split[1]] );
		}
	}
	public static function getConfigSection($section_name){
		self::loadFile();
		$configSection = parse_ini_file(self::$path."/../".self::$config_file_name, true);
		if( !$configSection ){
			throw new MagratheaException("There was an error trying to load the config file.<br/>");
		}
		return $configSection[$section_name];
	}
}


class MagratheaConfig { 
	private $path = __DIR__;
	private $config_file_name = "configs/magrathea_plus.conf";
	private $configs = null;

	public function __construct(){
		$this->configs = null;
	}

	public function setPath($p){
		$this->path = $p;
	}
	public function setConfig($c){
		$this->configs = $c;
	}
	public function setFile($filePath){
		$this->config_file_name = $filePath;
	}
	private function loadFile(){
		if(!file_exists($this->path.$this->config_file_name)){
			throw new MagratheaException("Config file could not be found - ".$this->path.$this->config_file_name);
		}
	}
	public function createFileIfNotExists(){
		if(!file_exists($this->path.$this->config_file_name)){
			return $this->Save();
		} else return true;
	}
	public function getConfig($config_name=""){
		if( is_null($this->configs) ){
			$this->loadFile();
			$this->configs = parse_ini_file($this->path.$this->config_file_name, true);
		}
		if( empty($config_name) ){
			return $this->configs;
		} else {
			$c_split = explode("/", $config_name);
			return ( count($c_split) == 1 ? $this->configs[$config_name] : $this->configs[$c_split[0]][$c_split[1]] );
		}
	}
	public function getConfigSection($section_name){
		$this->loadFile();
		$configSection = @parse_ini_file($this->path.$this->config_file_name, true);
		if( empty($configSection ) ) return null;
		if( !$configSection ){
			throw new MagratheaException("There was an error trying to load the config file.<br/>");
		}
		return $configSection[$section_name];
	}
	public function Save($save_sections=true) { 
		$content = "// generated by Magrathea at ".@date("Y-m-d h:i:s")."\n";
		$data = $this->configs;
		if( $data == null ) $data = array();
		if ($save_sections) { 
			foreach ($data as $key=>$elem) { 
				$content .= "\n[".$key."]\n"; 
				if(!is_array($elem)){
					throw new MagratheaConfigException("Hey, you! If you are gonna save a config file with sections, all the configs must be inside one section...", 1);
					
				}
				foreach ($elem as $key2=>$elem2) { 
					if(is_array($elem2)) { 
						for($i=0;$i<count($elem2);$i++) { 
							$content .= "\t".$key2."[] = \"".$elem2[$i]."\"\n"; 
						} 
					} else if($elem2=="") $content .= "\t".$key2." = \n"; 
					else $content .= "\t".$key2." = \"".$elem2."\"\n"; 
				} 
			} 
		} else { 
			foreach ($data as $key=>$elem) { 
				if(is_array($elem)) { 
					for($i=0;$i<count($elem);$i++) { 
						$content .= $key."[] = \"".$elem[$i]."\"\n";
					} 
				} else if($elem=="") $content .= $key." = \n"; 
				else $content .= $key." = \"".$elem."\"\n"; 
			} 
		} 
		if(file_exists($this->path.$this->config_file_name)){
			unlink($this->path.$this->config_file_name);
		}
		if (!$handle = @fopen($this->path.$this->config_file_name, 'w')) { 
			throw new MagratheaConfigException("Oh noes! Could not open File: ".$this->path.$this->config_file_name, 1);
			return false; 
		} 
		if (!fwrite($handle, $content)) { 
			throw new MagratheaConfigException("Oh noes! Could not save File: ".$this->path.$this->config_file_name, 1);
			return false; 
		} 
		fclose($handle); 
		return true; 
	}

	
	
	
}

